# Generated by Django 4.1.7 on 2023-03-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='description',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
    ]
