# Generated by Django 4.1.7 on 2023-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_description_plan_activity_remove_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
    ]
