# Generated by Django 4.1.7 on 2023-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_plan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='time',
        ),
    ]
