# Generated by Django 4.1.7 on 2023-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_plan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time_spent',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
