# Generated by Django 4.1.7 on 2023-03-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_plan_time_spent_delete_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
