# Generated by Django 4.1.7 on 2023-03-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_plan_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='progress',
        ),
    ]
